import type { GetSolutionData, GetSolutionMeta } from "./solution"

export let solutionData: Array<GetSolutionData> = [
    {
      solution_id: 1,
      solution_user: 2,
      solution_exercise: 3,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 2,
      solution_user: 2,
      solution_exercise: 7,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 3,
      solution_user: 2,
      solution_exercise: 2,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 4,
      solution_user: 2,
      solution_exercise: 1,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 5,
      solution_user: 2,
      solution_exercise: 3,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 6,
      solution_user: 2,
      solution_exercise: 3,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 7,
      solution_user: 2,
      solution_exercise: 3,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
      solution_id: 8,
      solution_user: 2,
      solution_exercise: 3,
      solution_date: 4,
      solution_duration: 5,
      solution_pending: true,
      solution_correct: false,
      solution_content: {},
    },
    {
        solution_id: 9,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 10,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 11,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 12,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 13,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 14,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 15,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 16,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 17,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 18,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 19,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
      {
        solution_id: 20,
        solution_user: 2,
        solution_exercise: 3,
        solution_date: 4,
        solution_duration: 5,
        solution_pending: true,
        solution_correct: false,
        solution_content: {},
      },
  ];

export let solutionMeta: GetSolutionMeta = {
    next_page: 2,
    next_url: 2,
    page_size: 10,
    pages: 2,
    prev_page: 0,
    prev_url: 0,
    total: 20,
  };